name: Allocate CloudBees CD/RO resource
description: Allocate CloudBees CD/RO resource in order to get exclusive access to the machine

inputs:
  ACTION:
    required: true
    choices: ['lock', 'unlock']
  CB_USER:
    required: true
  CB_PASSWORD:
    required: true

runs:
  using: 'composite'
  steps:
    - name: allocate
      shell: bash
      env:
        CB_USER: ${{ inputs.CB_USER }}
        CB_PASSWORD: ${{ inputs.CB_PASSWORD }}
      run: |
        machine="$(hostname -s)"

        python3.12 ${{ github.workspace }}/.github/scripts/allocate_cb_resource.py --${{ inputs.ACTION }} "$machine"
