name: Setup Intel oneAPI toolkit
description: Common action to setup Intel oneAPI toolkit

inputs:
  INTEL_ONEAPI_TOOLKIT_DOWNLOAD_URL:
    description: URL to download Intel oneAPI toolkit
    required: true

runs:
  using: composite
  steps:

    - uses: actions/cache/restore@v4
      id: cache-oneapi
      with:
        path: ${{ github.workspace }}/oneapi
        key: oneapi-${{ inputs.INTEL_ONEAPI_TOOLKIT_DOWNLOAD_URL }}-${{ hashFiles('**/get_oneapi_component.py') }}

    - name: Download oneAPI toolkit
      if: steps.cache-oneapi.outputs.cache-hit != 'true'
      shell: bash
      run: >
        python3.12 "${{ github.workspace }}/.github/scripts/get_oneapi_component.py" 
        --installer-url ${{ inputs.INTEL_ONEAPI_TOOLKIT_DOWNLOAD_URL }}
        --destination "${{ github.workspace }}/oneapi"

    - uses: actions/cache/save@v4
      if: always() && steps.cache-oneapi.outputs.cache-hit != 'true'
      with:
        path: ${{ github.workspace }}/oneapi
        key: oneapi-${{ inputs.INTEL_ONEAPI_TOOLKIT_DOWNLOAD_URL }}-${{ hashFiles('**/get_oneapi_component.py') }}

    - name: Setup oneAPI toolkit env
      shell: bash
      run: |
        source "${{ github.workspace }}/oneapi/setvars.sh"
        echo "$PATH" >> "$GITHUB_PATH"
        {
          echo "CC=icx"
          echo "CXX=icpx"
          echo "C_INCLUDE_PATH=$CMPLR_ROOT/include:$C_INCLUDE_PATH"
          echo "CPLUS_INCLUDE_PATH=$CMPLR_ROOT/include:$CPLUS_INCLUDE_PATH"
          echo "LD_LIBRARY_PATH=$CMPLR_ROOT/lib:$LD_LIBRARY_PATH"
        } >> "$GITHUB_ENV"
