name: Setup Intel oneMKL
description: Common action to setup Intel oneMKL

inputs:
  ONEMKL_DOWNLOAD_URL:
    description: URL to download Intel oneMKL
    required: true

runs:
  using: composite
  steps:

    - uses: actions/cache/restore@v4
      id: cache-onemkl
      with:
        path: ${{ github.workspace }}/oneapi/mkl
        key: onemkl-${{ inputs.ONEMKL_DOWNLOAD_URL }}-${{ hashFiles('**/get_oneapi_component.py') }}}

    - name: Download oneMKL
      if: steps.cache-onemkl.outputs.cache-hit != 'true'
      shell: bash
      run: >
        python3.12 "${{ github.workspace }}/.github/scripts/get_oneapi_component.py" 
        --installer-url ${{ inputs.ONEMKL_DOWNLOAD_URL }}
        --destination "${{ github.workspace }}/oneapi"

    - uses: actions/cache/save@v4
      if: always() && steps.cache-onemkl.outputs.cache-hit != 'true'
      with:
        path: ${{ github.workspace }}/oneapi/mkl
        key: onemkl-${{ inputs.ONEMKL_DOWNLOAD_URL }}-${{ hashFiles('**/get_oneapi_component.py') }}}

    - name: Setup oneMKL env
      shell: bash
      run: |
        source "${{ github.workspace }}/oneapi/mkl/latest/env/vars.sh"
        echo "$PATH" >> "$GITHUB_PATH"
        {
          echo "MKLROOT=$MKLROOT"
          echo "CPATH=$CPATH"
          echo "LIBRARY_PATH=$LIBRARY_PATH"
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        } >> "$GITHUB_ENV"
