name: Setup SYCL compiler
description: Common action to setup SYCL compiler

inputs:
  SYCL_COMPILER_VERSION:
    description: Version of SYCL compiler to setup (e.g. nightly-2024-05-16)
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v4
      id: cache-sycl
      with:
        path: ${{ github.workspace }}/sycl
        key: sycl-${{ inputs.SYCL_COMPILER_VERSION }}-${{ hashFiles('**/get_intel_llvm_compiler.py') }}

    - name: Download SYCL compiler
      if: steps.cache-sycl.outputs.cache-hit != 'true'
      shell: bash
      run: >
        python3.12 "${{ github.workspace }}/.github/scripts/get_intel_llvm_compiler.py"
        --compiler-version ${{ inputs.SYCL_COMPILER_VERSION }}
        --destination "${{ github.workspace }}/sycl"

    - uses: actions/cache/save@v4
      if: always() && steps.cache-sycl.outputs.cache-hit != 'true'
      with:
        path: ${{ github.workspace }}/sycl
        key: sycl-${{ inputs.SYCL_COMPILER_VERSION }}-${{ hashFiles('**/get_intel_llvm_compiler.py') }}

    - name: Setup SYCL compiler env
      shell: bash
      run: |
        sycl_dir="${{ github.workspace }}/sycl"
        echo "$sycl_dir/bin" >> "$GITHUB_PATH"
        {
          echo "CPATH=$sycl_dir/include:$sycl_dir/include/sycl:$CPATH"
          echo "LD_LIBRARY_PATH=$sycl_dir/lib:$LD_LIBRARY_PATH"
        } >> "$GITHUB_ENV"
