name: codeplay-install-driver
description: Download and unpack Intel graphics drivers
inputs:
  GPU:
    description: "Install for PVC or BMG gpu"
    type: string
  IGC:
    description: "Use ROLLING or STAGING release"
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Intel graphics drivers
      if: inputs.IGC == 'ROLLING'
      shell: bash
      run: |                
        export no_proxy="127.0.0.1,localhost"
        if [[ "${{ inputs.GPU }}" == "BMG" ]]; then
          sudo -E add-apt-repository ppa:kobuk-team/intel-graphics
          echo -e "Package: *\nPin: release o=LP-PPA-kobuk-team-intel-graphics\nPin-Priority: 1001" \
            | sudo tee /etc/apt/preferences.d/kobuk-driver
          sudo -E apt update
        else
          sudo -E apt update
          sudo -E apt install --allow-downgrades -y \
            intel-media-va-driver-non-free libmfx-gen1 libvpl2 \
            libegl-mesa0 libegl1-mesa-dev libgl1-mesa-dev  \
            libgles2-mesa-dev libigdgmm12 libxatracker2 mesa-va-drivers \
            mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all vainfo \
            libigc-dev intel-igc-cm libigdfcl-dev libigfxcmrt-dev libze-dev hwinfo
        fi
        sudo -E apt-get install --allow-downgrades -y libze-intel-gpu1 libze-dev intel-metrics-discovery \
          intel-opencl-icd ocl-icd-opencl-dev clinfo intel-gsc intel-ocloc g++
        dpkg -l | grep libhwloc15 > /dev/null || sudo -E apt install --allow-downgrades -y libhwloc15
        echo "DRIVER_VERSION=$(dpkg-query -W -f='${Version}\n' libze-intel-gpu1)" >> "$GITHUB_ENV"
    - name: Install Intel graphics drivers
      if: inputs.IGC == 'STAGING'
      shell: bash
      run: |
        export no_proxy="127.0.0.1,localhost"
        if [[ "${{ inputs.GPU }}" == "BMG" ]]; then
          echo -e "Package: *\nPin: release o=LP-PPA-kobuk-team-intel-graphics-staging\nPin-Priority: 1001" \
            | sudo tee /etc/apt/preferences.d/kobuk-driver
          sudo -E add-apt-repository ppa:kobuk-team/intel-graphics-staging
          sudo -E apt update
          sudo -E apt-get install --allow-downgrades -y libze-intel-gpu1 libze-dev intel-metrics-discovery \
            intel-opencl-icd ocl-icd-opencl-dev clinfo intel-gsc intel-ocloc g++
          dpkg -l | grep libhwloc15 > /dev/null || sudo -E apt install --allow-downgrades -y libhwloc15
          echo "DRIVER_VERSION=$(dpkg-query -W -f='${Version}\n' libze-intel-gpu1)" >> "$GITHUB_ENV"
        else
          exit 1
        fi
