name: Test
description: Common action to run tests for CUTLASS/XeTLA 

inputs:
  PROJECT:
    description: Project to test
    required: true
    default: ""
  TARGETS:
    description: Targets to run
    required: true

runs:
  using: composite
  steps:
    - name: Run tests
      shell: bash
      id: tests
      run: |
        source "$GITHUB_WORKSPACE/.github/scripts/print_message.sh"

        if [ -n "${{ inputs.PROJECT }}" ]; then
            cd "$GITHUB_WORKSPACE/${{ inputs.PROJECT }}/build" || exit 1
        else
            cd "$GITHUB_WORKSPACE/build" || exit 1
        fi

        test_outputs="$GITHUB_WORKSPACE/outputs/testing"
        mkdir -p "$test_outputs"

        IFS=' ' read -r -a TARGETS <<< "${{ inputs.TARGETS }}"

        for target in "${TARGETS[@]}"; do
          print_message "Running target: $target" blue
          ctest -V --output-on-failure --timeout 7200 -R "$target" | tee "$test_outputs/$target"_test.log
          if [ $? -ne 0 ]; then
            echo -e "::error:: $target failed to run or was not found"
            echo "test_failed=1" >> "$GITHUB_OUTPUT"
            print_message "Failed to run target: $target" bright_red
          else
            print_message "Successfully ran target: $target" bright_green
          fi
        done
