name: Build
description: Common action to build CUTLASS/XeTLA tests

inputs:
  PROJECT:
    description: Project to build
    required: true
    default: ""
  TARGETS:
    description: Targets to build
    required: true

runs:
  using: composite
  steps:
    - name: Build tests
      shell: bash
      id: build
      run: |
        source "$GITHUB_WORKSPACE/.github/scripts/print_message.sh"

        if [ -n "${{ inputs.PROJECT }}" ]; then
            cd "$GITHUB_WORKSPACE/${{ inputs.PROJECT }}/build" || exit 1
        else
            cd "$GITHUB_WORKSPACE/build" || exit 1
        fi

        IFS=' ' read -r -a TARGETS <<< "${{ inputs.TARGETS }}"

        for target in "${TARGETS[@]}"; do
          print_message "Building target: $target" blue
          if ! ninja -v "$target"; then
            echo -e "::error:: $target failed to build or was not found"
            echo "build_failed=1" >> "$GITHUB_OUTPUT"
            print_message "Failed to build target: $target" bright_red
          else
            print_message "Successfully built target: $target" bright_green
          fi
        done

