name: Setup Driver
description: Common action to setup Intel GPU driver

inputs:
  DRIVER_VERSION:
    description: Version of driver to install
    required: true
  DRIVER_BRANCH:
    description: Branch of driver to install
    required: true
  DRIVER_REPO:
    description: Repository of driver to install
    required: true
  DRIVER_PATH:
    description: Path to driver to install
    required: true
  ARTIFACTORY_USER:
    description: Username for Artifactory
    required: true
  ARTIFACTORY_TOKEN:
    description: Token for Artifactory
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v4
      id: cache-driver
      with:
        path: ${{ github.workspace }}/driver/unpacked
        key: driver-${{ inputs.DRIVER_VERSION }}-${{ hashFiles('**/get_driver.py') }}

    - name: Download Intel GPU driver
      shell: bash
      if: steps.cache-driver.outputs.cache-hit != 'true'
      env:
        ARTIFACTORY_USER: ${{ inputs.ARTIFACTORY_USER }}
        ARTIFACTORY_TOKEN: ${{ inputs.ARTIFACTORY_TOKEN }}
        GITHUB_USER: ${{ inputs.GITHUB_USER }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: >-
        python3.12 "${{ github.workspace }}/.github/scripts/get_driver.py"
        --destination "${{ github.workspace }}/driver"
        internal
        --driver-branch "${{ inputs.DRIVER_BRANCH }}"
        --driver-version "${{ inputs.DRIVER_VERSION }}"
        --driver-repo "${{ inputs.DRIVER_REPO }}"
        --driver-path "${{ inputs.DRIVER_PATH }}"

    - uses: actions/cache/save@v4
      if: always() && steps.cache-driver.outputs.cache-hit != 'true'
      with:
        path: ${{ github.workspace }}/driver/unpacked
        key: driver-${{ inputs.DRIVER_VERSION }}${{ hashFiles('**/get_driver.py') }}

    - name: Setup Intel GPU driver env
      shell: bash
      run: |
        unpacked_dir="${{ github.workspace }}/driver/unpacked"
        echo "$unpacked_dir/usr/bin" >> "$GITHUB_PATH"
        {
          echo "ZE_AFFINITY_MASK=0"
          echo "LIBRARY_PATH=$unpacked_dir/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH"
          echo "LD_LIBRARY_PATH=$unpacked_dir/usr/lib/x86_64-linux-gnu/intel-opencl:$unpacked_dir/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
          echo "IGC_EnableVISANoSchedule=1"
          echo "IGC_ShaderDumpEnable=1"
          echo "IGC_DumpToCustomDir=./mm_dumps"
          echo "IGC_VATemp=1"
          echo "ONEAPI_DEVICE_SELECTOR=level_zero:gpu"
        } >> "$GITHUB_ENV"
