name: Benchmarks
description: Common action to run CUTLASS SYCL/CUDA benchmarks

inputs:
  PLATFORM:
    description: Platform to run benchmarks on
    required: true
  INPUT:
    description: Config files with inputs to run benchmarks
    required: true
  DEFAULT_BENCHMARKS_BIN:
    description: Default benchmarks binary path
    required: true

runs:
  using: composite
  steps:
    - name: Run benchmarks
      shell: bash
      id: benchmarks
      run: |
        source "$GITHUB_WORKSPACE/.github/scripts/print_message.sh"

        cd "$GITHUB_WORKSPACE/build" || exit 1

        benchmarks_output="$GITHUB_WORKSPACE/outputs/testing"
        mkdir -p "$benchmarks_output"

        export BENCHMARK_FORMAT="console"
        export BENCHMARK_OUT_FORMAT="json"
        
        input_files=($GITHUB_WORKSPACE/benchmarks/device/${{ inputs.INPUT }}/input_files/*.in)
        
        set +e
        for input_file in "${input_files[@]}"; do
          
          file_name="${input_file##*/}"          
          if [[ $file_name =~ input_(.*)\.in$ ]]; then
            group="${BASH_REMATCH[1]}"
          else
            group="Default"
          fi
          
          export BENCHMARK_OUT="$benchmarks_output/${{ inputs.PLATFORM }}_"$group"_benchmarks.log"
        
          print_message "Running CUTLASS benchmarks for ${{ inputs.INPUT }} $group" blue
          
          benchmarks_dir=$(dirname "$(grep -lr  "$file_name" "$GITHUB_WORKSPACE/benchmarks/" | grep "CMakeLists.txt")")
          benchmarks_dir="${benchmarks_dir#$GITHUB_WORKSPACE/}"
          benchmarks_bin=($GITHUB_WORKSPACE/build/$benchmarks_dir/cutlass_benchmarks_*)
          
          if [[ $benchmarks_bin == "$GITHUB_WORKSPACE/build/$benchmarks_dir/cutlass_benchmarks_*" ]]; then
            benchmarks_bin=${{ inputs.DEFAULT_BENCHMARKS_BIN }}
          fi
          
          "$benchmarks_bin" --config_file="$input_file"
          if [ $? -ne 0 ]; then
            echo -e "::error:: Failed to run benchmarks for ${{ inputs.INPUT }} $group"
            echo "benchmarks_failed=1" >> "$GITHUB_OUTPUT"
            print_message "Failed to run benchmarks for ${{ inputs.INPUT }} $group" bright_red
          else
            print_message "Successfully ran benchmarks for ${{ inputs.INPUT }} $group" bright_green
          fi
        done
