name: codeplay-install-dpcpp
description: Download and unpack DPC++ nightly release
inputs:
  DPCPP_RELEASE:
    description: "Use RELEASE or NIGHTLY DPC++ release"
    type: string
    default: NIGHTLY
  DPCPP_VERSION:
    description: "DPC++ version to use"
    type: string
  DPCPP_PATH:
    description: Path to DPC++
    type: string
    default: ~/dpcpp
  GH_TOKEN:
    description: "PAT token to use gh api"
    type: string

runs:
  using: "composite"
  steps:
    - name: Install DPCPP
      if: inputs.DPCPP_RELEASE == 'NIGHTLY'
      shell: bash
      run: |
        export no_proxy="127.0.0.1,localhost"
        export DPCPP_PATH=${{ inputs.DPCPP_PATH }}
        mkdir -p $DPCPP_PATH
        pushd $DPCPP_PATH
        if [[ "${{ inputs.DPCPP_VERSION }}" != "" ]]; then
          echo "Will use DPCPP ${{ inputs.DPCPP_VERSION }}"
          URL=https://github.com/intel/llvm/releases/download/${{ inputs.DPCPP_VERSION }}/sycl_linux.tar.gz;
        else
          echo "Will use latest DPCPP version"
          latest=$(curl -H 'authorization: Bearer ${{ inputs.GH_TOKEN }}' -sS https://api.github.com/repos/intel/llvm/releases | jq -r '[.[].tag_name|select(match("nightly-[0-9]{4}-[0-9]{2}-[0-9]{2}"))][0]')
          URL=https://github.com/intel/llvm/releases/download/${latest}/sycl_linux.tar.gz;
        fi
        echo "Downloading DPCPP from ${URL}"
        sudo wget -q $URL
        sudo tar -xf sycl_linux.tar.gz
        sudo rm sycl_linux.tar.gz
        popd
        echo "$PATH" >> "$GITHUB_PATH"
        {
          echo "PATH=$DPCPP_PATH/bin:$PATH"
          echo "C_INCLUDE_PATH=$DPCPP_PATH/include:$C_INCLUDE_PATH"
          echo "CPLUS_INCLUDE_PATH=$DPCPP_PATH/include:$CPLUS_INCLUDE_PATH"
          echo "LD_LIBRARY_PATH=$DPCPP_PATH/lib:$LD_LIBRARY_PATH"
          echo "CC=$DPCPP_PATH/bin/clang"
          echo "CXX=$DPCPP_PATH/bin/clang++"
        } >> "$GITHUB_ENV"

    - name: Install DPCPP
      if: inputs.DPCPP_RELEASE == 'RELEASE'
      shell: bash
      run: |
        export no_proxy="127.0.0.1,localhost"
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt update
        sudo apt install -y intel-oneapi-runtime-libs intel-oneapi-compiler-dpcpp-cpp
        source /opt/intel/oneapi/setvars.sh
        echo "$PATH" >> "$GITHUB_PATH"
        {
          echo "CC=icx"
          echo "CXX=icpx"
          echo "C_INCLUDE_PATH=$CMPLR_ROOT/include:$C_INCLUDE_PATH"
          echo "CPLUS_INCLUDE_PATH=$CMPLR_ROOT/include:$CPLUS_INCLUDE_PATH"
          echo "LD_LIBRARY_PATH=$CMPLR_ROOT/lib:$LD_LIBRARY_PATH"
        } >> "$GITHUB_ENV"
