name: "Cuda Test"

on:
  push:
    branches: [ "sycl-develop" ]
  pull_request:
    branches: [ "sycl-develop" ]
  merge_group:
    branches: [ "sycl-develop" ]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run cuda tests
    runs-on: cp-nvidia-gpu
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Build
        shell: bash
        run: |
          nvidia-smi
          export CUDACXX=/usr/local/cuda/bin/nvcc
          cmake -G Ninja -DCUTLASS_NVCC_ARCHS="90a"

      - name: Unit test
        shell: bash
        run: |
          cmake --build . --target test_unit -j 48
