name: Sync internal repo with cutlass-fork/sycl-develop

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: [ service ]

    if: github.ref == 'refs/heads/sycl-develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: sycl-develop
          fetch-depth: 0

      - name: Configure user
        run: |
          git config user.name 'perflibs'
          git config user.email 'perflibs@intel.com'

      - name: Add upsteam
        run: |
          if ! git remote | grep -q upstream; then
            git remote add upstream https://github.com/codeplaysoftware/cutlass-fork.git
          fi
          git fetch upstream

      - name: Merge changes from upstream
        run: |
          git merge --no-ff upstream/sycl-develop
        continue-on-error: true

      - name: Keep internal .github files always
        if: failure() || success()
        run: |
          if git ls-files -u | grep -q '.github'; then
            git rm -r .github
            git checkout HEAD -- .github
            git commit --no-edit
          fi

      - name: Push changes
        run: |
          git checkout sycl-develop 2>/dev/null || git checkout -b sycl-develop
          git push https://perflibs:${{ env.PAT }}@github.com/intel-collab/libraries.ai.cutlass.internal.git sycl-develop
        env:
          PAT: ${{ secrets.PAT }}
