name: Workflow API

on:
  push:
    branches: [ intel_gpu_backend_pipeline ]
  pull_request:
    branches: [ intel_gpu_backend_pipeline ]

jobs:
  workflow_api:
    name: Trigger Workflow API
    runs-on: [ service ]
    steps:
      - name: get-certificate
        run: |
            wget https://certificates.intel.com/repository/certificates/IntelSHA384RootCA-Base64.crt -O trust.crt
            echo "CURL_CA_BUNDLE=$GITHUB_WORKSPACE/trust.crt" >> "$GITHUB_ENV"
      - name: workflow-api
        uses: intel-innersource/frameworks.actions.workflow-api@v1
